// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWSEJhNWbNhR7CkF-gKdR87JRYs-wmncg',
    appId: '1:1081775063628:web:3fec7cb9fb4d3bf68baae9',
    messagingSenderId: '1081775063628',
    projectId: 'news-app-rest-api',
    authDomain: 'news-app-rest-api.firebaseapp.com',
    storageBucket: 'news-app-rest-api.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk9MHLNvjPy-VSH6oP1vFXRL9er7jLvHM',
    appId: '1:1081775063628:android:0072056abb835ca88baae9',
    messagingSenderId: '1081775063628',
    projectId: 'news-app-rest-api',
    storageBucket: 'news-app-rest-api.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp4c9oemYImpqfBMAbLokh1j7XdTyhW_8',
    appId: '1:1081775063628:ios:c6b625ed7fb9b89d8baae9',
    messagingSenderId: '1081775063628',
    projectId: 'news-app-rest-api',
    storageBucket: 'news-app-rest-api.appspot.com',
    iosClientId: '1081775063628-cq46ja6gsgvcuv1o4q3dmvp1ieescat0.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp4c9oemYImpqfBMAbLokh1j7XdTyhW_8',
    appId: '1:1081775063628:ios:cd30c3a251be2e868baae9',
    messagingSenderId: '1081775063628',
    projectId: 'news-app-rest-api',
    storageBucket: 'news-app-rest-api.appspot.com',
    iosClientId: '1081775063628-tusjg27k3ijfoe4nrtlb3vp19cc9d2ba.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsApp.RunnerTests',
  );
}
